config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  get 'user/show'
  get 'user/follow_list', to: 'user#follow_list'
  devise_for :users
  root to: "top#index"
  get 'top/index'
  get 'top/show'
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
  
  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  # ================================
  # リレーション参考文献：
  # https://qiita.com/mitsumitsu1128/items/e41e2ff37f143db81897
  # ================================

  has_many :relationships
  # followingsクラス（model）は存在しないため、through: :relationshipsとして中間テーブルを明示
  # source: :followとして、relationshipsテーブルのfollow_idを参考にして、followingsモデルにアクセスするよう明示
  has_many :followings, through: :relationships, source: :follow
  # reverse_of_relationshipsクラス（model）は存在しないため、class_name: 'Relationshipとしてrelationsipモデルの事だと明示
  # foreign_key: 'follow_id'とすることでrelaitonshipsテーブルにアクセスする時、follow_idを使うよう明示
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  # followersクラス（model）は存在しないため、through: :reverses_of_relationshipとして中間テーブルを明示
  # source: :userとして、user_idを参考にするよう明示
  has_many :followers, through: :reverse_of_relationships, source: :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # メール送信した場合は「:confirmable」を追加する
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable, :timeoutable, :trackable, :omniauthable, omniauth_providers:[:twitter]

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def get_follow_list
    self.followings
  end

  def get_followers_list
    self.followers
  end

  def matching
    target_list = []
    list = []
    targets = self.relationships.pluck(:follow_id)
    targets.each do |u|
        if match = Relationship.find_by(user_id: u, follow_id: self.id)
        target_list << match.user_id
      end
    end
    target_list.each do |u|
      list << User.find(u)
    end
    list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  # ログイン後の遷移先設定
  # testtesttesttest
  def after_sign_in_path_for(resource)
    user_show_path
  end

  private
  def sign_in_required
    redirect_to new_user_session_url unless user_signed_in?
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'フォローしました'
      redirect_to user_index_url
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to user_index_url
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:warn] = 'フォローを解除しました'
      redirect_to user_index_url
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to user_index_url
    end
  end

  private
  
  def set_user
    # @user = User.find(params[:relationship][:follow_id])
    @user = User.find(params[:follow_id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :sign_in_required, only: [:show]
  def index
  end

  def show
  end

# def test
#  hogehoge
# end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def show

  end

  def follow_list
    @follow_list = current_user.get_follow_list
    @followers_list = current_user.get_followers_list
    @match_list = current_user.matching
  end

  # def test_code
  #   処理・・・・
  #   処理・・・・
  #   処理・・・・
  #   処理・・・・
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayGround</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <div class="nav-wrapper">
          <a href="/" class="brand-logo"><i class="material-icons">cloud</i>PlayGroundAPP</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if user_signed_in? %>
              <li><%= link_to current_user.username, user_show_path %></li>
              <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'サインアップ', new_user_registration_path %></li>
              <li><%= link_to 'ログイン', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <!-- ここに追加 -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー解除', class: 'waves-effect orange accent-3 btn' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローする', class: 'btn waves-effect waves-lighten-2 btn' %>
    <% end %>
  <% end %>
<% end %>

app/views/top/index.html.erb
<div class="parallax-container">
  <%= image_tag 'startup-594091_1920.jpg'%>
</div>
<div class="section white">
  <div class="row container">
    <h2 class="header">Matching App Sample</h2>
    <p class="grey-text text-darken-3 lighten-3">Parallax is an effect where the background content or image in this case, is moved at a different speed than the foreground content while scrolling.</p>
  </div>
</div>

app/views/user/_menu.html.erb
<%
=begin%>
 <div>
  <%= link_to 'MyPageへ', user_show_path %>
  <%= link_to 'User一覧', user_index_path %>
  <%= link_to 'マッチング一覧', "" %>
</div> 
<%
=end%>

<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s4"><%= link_to 'MyPage', user_show_path %></li>
      <li class="tab col s4"><%= link_to 'User一覧', user_index_path %></li>
      <li class="tab col s4"><%= link_to 'マッチング一覧', user_follow_list_path %></li>
    </ul>
  </div>
</div>
<hr>

app/views/user/follow_list.html.erb
<h3>マッチング一覧</h3>
<%= render 'user/menu' %>
<div class="container green lighten-2 z-depth-4">
  <div class="row">
    <blockquote>フォロー中</blockquote>
    <% @follow_list.each do |user| %>
      <div class="col s3">
        <div class="card  hoverable">
          <div class="card-image">
            <%= image_tag 'sample-1.jpg' %>
          </div>
          <div class="card-content" >
              <p><i class="material-icons">sentiment_very_satisfied</i>&nbsp;<%= user.username %></p>
              <p><i class="material-icons">email</i>&nbsp;<%= user.email %></p>
          </div>
          <div class="card-action">
            <%= render 'relationships/follow_button', user: user %>
          </div>
        </div>
      </div>
    <% end %> 
  </div>
</div>
<br>
<div class="container blue-grey lighten-5 z-depth-4">
  <div class="row">
    <blockquote>フォローされている人</blockquote>
    <% @followers_list.each do |user| %>
      <div class="col s3">
        <div class="card  hoverable">
          <div class="card-image">
            <%= image_tag 'sample-1.jpg' %>
          </div>
          <div class="card-content" >
              <p><i class="material-icons">sentiment_very_satisfied</i>&nbsp;<%= user.username %></p>
              <p><i class="material-icons">email</i>&nbsp;<%= user.email %></p>
          </div>
          <div class="card-action">
            <%= render 'relationships/follow_button', user: user %>
          </div>
        </div>
      </div>
    <% end %> 
  </div>
</div>
<br>
<div class="container green lighten-2 z-depth-4">
  <div class="row">
    <blockquote>マッチした人</blockquote>
    <% @match_list.each do |user| %>
      <div class="col s3">
        <div class="card  hoverable">
          <div class="card-image">
            <%= image_tag 'sample-1.jpg' %>
          </div>
          <div class="card-content" >
              <p><i class="material-icons">sentiment_very_satisfied</i>&nbsp;<%= user.username %></p>
              <p><i class="material-icons">email</i>&nbsp;<%= user.email %></p>
          </div>
          <div class="card-action">
            <%= render 'relationships/follow_button', user: user %>
          </div>
        </div>
      </div>
    <% end %> 
  </div>
</div>

app/views/user/index.html.erb
# ユーザの一覧を表示する

<h3>ユーザ一覧</h3>
<%= render 'user/menu' %>
<% if flash.any? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% key = "success" if key == "success" %>
      <% key = "warning" if key == "warn" %>
      toastr['<%= key %>']('<%= value %>');
    <% end %>
  </script>
<% end %>
<div class="row container">
  <% @users.each do |user| %>
    <% unless user.id == current_user.id%>
      <div class="col s4">
        <div class="card  hoverable">
          <div class="card-image">
            <%= image_tag 'sample-1.jpg' %>
          </div>
          <div class="card-content" >
              <p><i class="material-icons">sentiment_very_satisfied</i>&nbsp;<%= user.username %></p>
              <p><i class="material-icons">email</i>&nbsp;<%= user.email %></p>
          </div>
          <div class="card-action">
            <%= render 'relationships/follow_button', user: user %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %> 
</div>

app/views/user/show.html.erb
<h3>こんにちは、<%= current_user.username %>さん</h3>
<%= render 'user/menu' %>

<div class="row">
  <div class="col s5">
    <div class="card horizontal">
      <div class="card-image">
        <%= image_tag 'sample-1.jpg'%>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <label for="icon_prefix">ニックネーム</label>
          <p><%= current_user.username%></p>
          <label for="icon_prefix">登録アドレス</label>
          <p><%= current_user.email%></p>
          <br>
          <label for="icon_prefix">フォロー数</label>
          <p><%= current_user.followings.count %></p>
          <label for="icon_prefix">フォワー数</label>
          <p><%= current_user.followers.count %></p>
        </div>
      </div>
    </div>
  </div>
            
  <div class="col s3">
    <div class="card-panel green lighten-2">
      <div class="chip">
        <%= current_user.created_at %>
      </div>
      <div class="chip">
        <%= current_user.created_at %>
      </div>
    </div>
  </div>
  <div class="col s3">
    <div class="card-panel green lighten-2">
      <div class="chip">
        <%= current_user.created_at %>
      </div>
      <div class="chip">
        <%= current_user.created_at %>
      </div>
    </div>
  </div>
  <div class="col s6">
    <div class="card-panel blue-grey lighten-5">
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">textsms</i>
          <input type="text" id="autocomplete-input" class="autocomplete">
        </div>
      </div>
  </div>
</div>